apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: department-ingress
spec:
  rules:
    - http:
      - path: /department
        backend:
          serviceName: department-service
          servicePort: 32039

